# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29c3a740bb4bc6158ba1fa027e19146ed483bf7fb650ae5b40a48583e6773dc5e843e581cc9cacd68e7719dd5de4f530da21ad4150312d32b39cb55bb765a5ee

test:
  secret_key_base: 014d87864d620d91da8bd4c3ffce533f846f57fef27fe2eb9b3b20b3f8af6c2ed3147e0c41927f2a2d2d5ced3f5ee78b6ebd6f75c26819c73cb96f01f5553bc3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
